#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2012 José Miguel Molina <@_mvader> <hi@mvader.me>
# Fixed by Aarón Díaz R. <@AaronDiazR>

import pycurl, urllib2, re, sys

args = {'-s' : '', '-t' : '', '-c' : ''}
next_arg = ''
for arg in sys.argv[1:]:
    if arg in args.keys():
        next_arg = arg
    elif next_arg != '':
        args[next_arg] = arg
        next_arg = ''
    else:
        print "Parametro invalido %s" % arg
        break

if not args['-s'] or not args['-c']  or not args['-t']:
    print "Debes hacer una peticion del tipo subtitulos -s \"Nombre de la serie\" -t Temporada -c Capitulo"
else:
    show = args['-s']
    season = args['-t']
    chapter = args['-c']

    if len(chapter) == 1:
        chapter = '0' + chapter
    url = 'http://www.subtitulos.es/%s/%sx%s' % (show.lower().replace(' ', '-'), season, chapter)
    search = "http://www.subtitulos.es/updated/5/(?P<code>[0-9]+)/0"
    search_alt = "http://www.subtitulos.es/updated/4/(?P<code>[0-9]+)/0"
    codigo = ""
    
    hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'es-ES,es;q=0.8',
       'Connection': 'keep-alive',
       'Host': 'www.subtitulos.es'}
       
    page_content_req = urllib2.Request(url, headers=hdr)
    page_content = urllib2.urlopen(page_content_req).read()
    try:
        code = re.search(search, page_content).group(1)
        codigo = "5"
    except:
        try:
            code = re.search(search_alt, page_content).group(1)
            codigo = "4"
        except:
            print "No encontrado :("

    try:
        c = pycurl.Curl()
        c.setopt(c.URL, "http://www.subtitulos.es/updated/%s/%s/0" % (codigo, code))
        c.setopt(c.HTTPHEADER, ['Accept-Encoding: gzip, deflate, sdch',
                                'Accept-Language: es-ES,es;q=0.8',
                                'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36', 
                                'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 
                                'Referer: %s' % (url)])
        f = open('%s-%sx%s.srt' % (show.lower().replace(' ', '-'), season, chapter), 'wb')
        c.setopt(c.WRITEDATA, f)
        c.perform()
        print "Listo :)"
    except:
        print "Error al descargar el archivo :("
